### ISSUE TITLE
If like to expand the recipe

### ISSUE THREAD

**Issue by aaronlippold** [USGS-WSI-COOKBOOKS/stig#60]
Hi, I'd like to expand the cookbook to add more parameters to easily support DOD standards and NSA standards alongside the CIS standards. I'd like to reuse as much of the core code base as possible and somehow to figure out the most efficient pattern to create a second or third set of attributes for each organizational values. How would you guys suggest you would like to do this?

**Comment by isuftin** [comment]
@aaronlippold Because this cookbook is specific to the CIS STIG, you may want to create a new cookbook and reuse elements of the STIG cookbook which fit the DOD/NSA standards.
